config/routes.rb
Rails.application.routes.draw do
  resources :rescuecompts
  get 'location/map'

  resources :locations
  get 'user/index'

  get 'user/view'

  devise_for :users
  resources :complaints

root to: "complaints#index"

end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
belongs_to :user


has_attached_file :species_image, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "missing.jpg"
  validates_attachment_content_type :species_image, content_type: /\Aimage\/.*\Z/

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :user
end

app/models/rescuecompt.rb
class Rescuecompt < ActiveRecord::Base
		belongs_to :user
	belongs_to :complaint
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   has_many :complaints
   has_one :location
   has_attached_file :avatar, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) << :avatar
    devise_parameter_sanitizer.for(:account_update) << :avatar
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:sign_up) << :phno
    devise_parameter_sanitizer.for(:account_update) << :phno
    devise_parameter_sanitizer.for(:sign_up) << :role
    devise_parameter_sanitizer.for(:account_update) << :role
    devise_parameter_sanitizer.for(:sign_up) << :specialized
    devise_parameter_sanitizer.for(:account_update) << :specialized
    devise_parameter_sanitizer.for(:sign_up) << :reference_code
    devise_parameter_sanitizer.for(:account_update) << :reference_code
    devise_parameter_sanitizer.for(:sign_up) << :referred_by
    devise_parameter_sanitizer.for(:account_update) << :referred_by
  end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :find,:edit,:index]
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
   @complaints = Complaint.where(:user_id => current_user.id)
  @location = Location.new
 @location.user_id = current_user.id


 @complaints_filter= Complaint.where("user_id != ?",current_user.id).where("status != ?",true)

  @complaints_attending= Complaint.where(:rescuer_id => current_user.id)
  end

  def notified_complaints
  @complaints = Complaint.where(:user_id => current_user.id)
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
     @rescue_complaint = Rescuecompt.new
  @rescue_complaint.user_id = current_user.id
          #@user = Carpool.find(params[:format]).user
    @complaint_id=Complaint.find(params[:id]).id
    @latitude = Complaint.find(params[:id]).latitude
    @longitude = Complaint.find(params[:id]).longitude
    @city_name = Complaint.find(params[:id]).city_name
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
     @complaint = Complaint.new(complaint_params)
    #@complaint= @complaint.update(complaint_params)

    
    @complaint.user_id = current_user.id
    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        flash[:alert]= "Your location has been updated"
    
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def attend
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:species, :status, :city_name, :species_image, :latitude, :longitude,:user_id)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	
def new 
end

  def create

     @person = Location.where(:user_id => current_user.id).first
    
     if @person
     	  @user= @person.update(location_params)
     	  if @user
          flash[:alert]= "Your location has been updated"
     	      redirect_to root_path
     	  end
     else
       # @location = Location.new
       # @location.user_id = current_user.id
        @user= Location.create(location_params)
        @user.user_id = current_user.id 


          if @user.save
            flash[:alert]= "Your location has been updated"
     	      redirect_to root_path
     	    end
      end
	end


   def map
        @user = Complaint.find(params[:format]).user
        @latitude = Location.where(:user_id => @user.id).first.latitude
        @longitude = Location.where(:user_id => @user.id).first.longitude
   
   end


	private

	  def location_params
	  	params.require(:location).permit(:latitude, :longitude,:city_name)
	  end
end

app/controllers/rescuecompts_controller.rb
class RescuecomptsController < ApplicationController
def new 
end

 def create
      @rescue_complaint = Rescuecompt.new
      @rescue_complaint.user_id = current_user.id
      @rescue_complaint.complaint_id = current_user.id
     @person = Rescuecompt.where(:user_id => current_user.id).first 
     if @person
        @user= @person.update(location_params)
        if @user
          flash[:alert]= "Complaint will be attened by you"

          @complaint_id=@person.complaint_id;
          @save_complaint = Complaint.where(:id => @complaint_id).first
          @save_complaint.rescuer_id=current_user.id 
          @save_complaint.status=true
          @save_complaint.save

            redirect_to root_path
        end
     else
       # @location = Location.new
       # @location.user_id = current_user.id
        @user= Rescuecompt.create(location_params)
        @user.user_id = current_user.id 

    @complaint_id=@user.complaint_id;
      if @user.save
        flash[:alert]= "This complaint will be attened by you"

        redirect_to root_path
      end


  end
end



  
  def location_params
    params.require(:rescuecompt).permit(:complaint_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def view
  	@user= User.find(params[:id])
  end
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/rescuecompts_helper.rb
module RescuecomptsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/complaints/_form.html.erb
<%= form_for(@complaint,:html=>{:name=>"f",:onsubmit=>"getLocation(event);"})  do |f| %>
  <% if @complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% @complaint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :species %><br>
    <%= f.select :species, [['snake','snake'],['crocodile','crocodile'],['tiger','tiger'],['other','other']] %>
  </div>
  <div>
  Image upload: <%= f.file_field :species_image %>
  </div>

<!-- get latitude and longitude -->
  <%= f.hidden_field  :latitude %>
   <%= f.hidden_field  :longitude %>


 <%= f.hidden_field  :city_name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form' %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<p id="notice"><%= notice %></p>



<!-- ++++++++++ Listing of all notified Complaints to the rescuer +++++++++++++-->
<% if current_user.role=="rescuer" %>

<h1>Listing of all notified Complaints</h1>
<% if @complaints_filter.size >0  %>
<table>
  <thead>
    <tr>
      <th>User Name</th>
      <th>Species</th>
      <th>Date</th>
      <th>Status</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @complaints_filter.each do |complaint| %>
      <tr>
      <td><%= link_to "#{User.find(complaint.user_id).name}", user_view_path(:id => User.find(complaint.user_id).id) %> </td>
        <td><%= complaint.species %></td>
        <td><%= complaint.created_at.strftime("%d, %B, %Y")%></td>
        <td><% if complaint.status == false %>
            <%= "not yet attended" %>
            <% else %>
            <%= "help is on the way" %>
            <% end %>
        </td>
        <td><%= link_to 'Show', complaint %></td>
      </tr>
    <% end %>
  </tbody>
 <% else %>
  <h4>N0 notified Complaints</h4>
<% end %>

</table>

  <!--  ++++++++++  listing of all complaints rescuer is attending to  ++++++++++ -->
  <h1>Listing of all your attending Complaints</h1>
  <% if @complaints_attending.size >0 %>
  <table>
    <thead>
      <tr>
        <th>User Name</th>
        <th>Species</th>
        <th>Date</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @complaints_attending.each do |complaint| %>
        <tr>
           <td><%= link_to "#{User.find(complaint.user_id).name}", user_view_path(:id => User.find(complaint.user_id).id) %> </td></td>
          <td><%= complaint.species %></td>
          <td><%= complaint.created_at %></td>
          <td><%= link_to 'Show', complaint %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <h4>N0 Complaints to attend</h4>
  <% end %>

<% end %>
<!-- ++++++++++ Listing of all your Complaints +++++++++++++-->
<h1>Listing of all your Complaints</h1>
<% if @complaints.size >0 %>
<table>
  <thead>
    <tr>
      <th>Species</th>
      <th>Date</th>
      <th>Status</th>
      <th>Rescuer's name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.species %></td>
        <td><%= complaint.created_at.strftime("%d, %B, %Y") %></td>
        <td><% if complaint.status == false %>
            <%= "not yet attended" %>
            <% else %>
            <%= "help is on the way" %>
            <% end %>
        </td>

        <td><% if complaint.status == false %>
            <%= "" %>
            <% else %>
      
            <%= link_to "#{User.find(complaint.rescuer_id).name}",  user_view_path(:id => complaint.rescuer_id)%> 
            <% end %>
        </td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint),method: :get %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h4>NO complaints registered by you</h4>
<% end %>

<br>
<!-- for the user -->
<% if user_signed_in? %>
<%= link_to "new complaint",new_complaint_path %> 
<br>
<%= link_to "See all your complaints",complaints_path %> 
<br>

  <% if current_user.role == "rescuer" %>
  <%= render('location/form') %>
  <br>

  <% end %>
<% end %>

<br>

app/views/complaints/new.html.erb
<h1>New Complaint</h1>

<%= render 'form' %>

<%= link_to 'Back', complaints_path %>

app/views/complaints/notified_complaints.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Complaints</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Species</th>
      <th>Place</th>
      <th>Status</th>
      <th>Choice</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
       <% if complaint.status == false %>
      <tr>
        <td> complaint.created_at </td>
        <td><%= complaint.species %></td>
        <td><% if complaint.status == false %>
            <%= "not yet attended" %>
            <% else %>
            <%= "help is on the way" %>
            <% end %>
        </td>

        <td><% if complaint.status == false %>
            <%= "" %>
            <% else %>
      
            <%= link_to "#{complaint.rescuer_id.name}",  user_view_path(:id => complaint.user.id)%> 
            <% end %>
        </td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'save', edit_complaint_path(complaint),method: :get %></td>
       
         </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

app/views/complaints/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Complaint Details </h2>
<p>
  <strong>User name:</strong>
  <%= link_to "#{User.find(@complaint.user_id).name}", user_view_path(:id => User.find(@complaint.user_id).id) %> 
</p>
<p>
<%= image_tag @complaint.species_image.url(:thumb) %>
</p>
<p>
  <strong>Species:</strong>
  <%= @complaint.species %>
</p>

<p>
  <strong>Status:</strong>
  <%= @complaint.status %>
</p>
<p>
<strong>location:</strong>
<div class="map-show">
  <div id="latitude" style="display:none;">
  <%= @latitude %>
  </div>

  <div id="longitude" style="display:none;">
  <%= @longitude %>
  </div> 
  <% query = @latitude.to_s+","+@longitude.to_s %>
    <% first_result = Geocoder.search(query).first %>

  <div id="city_name" >
   <%= @city_name %>
  </div> 

  <p id="heading1">Users location</p>
  <div id="map-canvas3" style="border:1px solid red; height:400px;">

  </div>
</div>
</p>
<% if current_user.role == "rescuer" %>
<%= render('rescuecompts/form') %>
<% end %>
<br>
<% if current_user.id == @complaint.user_id%>
<%= link_to 'Edit', edit_complaint_path(@complaint) %> |
<%= link_to 'Back', complaints_path %>
<% else %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueApp</title>
<%= Gon::Base.render_data({}) %>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">
<!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>  -->
 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="login_nav">

  <% if !user_signed_in? %>
   <%= link_to "Sign up for user", new_user_registration_path %> or <%= link_to "log in for user", new_user_session_path %> <br>
  
   <% else %>
   <%= image_tag current_user.avatar.url(:thumb) %>
       Welcome <%= current_user.name %>.
       <%= link_to "edit your account", edit_user_registration_path %> .....
    <%= link_to "log out", destroy_user_session_path, :method => :delete %>
  <% end %>

 </div>

<%= yield %>

</body>
</html>

app/views/location/_form.html.erb
 <%= form_for(@location,:html=>{:name=>"f",:onsubmit=>"getLocation2(event);"}) do |f| %>
   <%= f.hidden_field  :latitude %>
   <%= f.hidden_field  :longitude %>
   <%= f.hidden_field  :city_name %>
    <%= f.submit "Publish location", class: "btn btn-blue btn-lg" %>
<% end %> 

app/views/location/map.html.erb
<div class="map-show">
	<div id="latitude" style="display:none;">
	<%= @latitude %>
	</div>

	<div id="longitude" style="display:none;">
	<%= @longitude %>
	</div> 
	<p id="heading1">Users location</p>
	<div id="map-canvas3" style="border:1px solid red; height:400px;">

	</div>
</div>

app/views/rescuecompts/_form.html.erb
 <%= form_for(@rescue_complaint,:html=>{:name=>"f",:onsubmit=>"post_attend(event);"}) do |f| %>
   <%= f.hidden_field  :complaint_id ,:value => @complaint_id %>
    <%= f.submit "attend complaint", class: "btn btn-blue btn-lg" %>
<% end %> 

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/view.html.erb
<h1>User Profile</h1>
<div class="user-profile">

<div id="user-profile-main">
	<span id="profile-details" class="font2">
		username : <%= @user.name %><br>
		email : <%= @user.email %><br>
		phone num : <%= @user.phno %><br>	
	</span>
	<% if @user.role=="rescuer" %>
		<div id="latitude" style="display:none;">
		<%=  Location.find_by_user_id(@user.id).latitude %>
		</div>

		<div id="longitude" style="display:none;">
		<%=  Location.find_by_user_id(@user.id).longitude %>
	
		</div> 
		<p id="heading1">Users location</p>
		<div id="map-canvas3" style="border:1px solid red; height:400px;">

		</div>
	<% end %>
</div>



</div>